version: '3'
services:
    web:
        image: vanminhph23/centos7.java8.idempiere:1.3
        container_name: his-app-8081-110-production
        restart: on-failure
        volumes:
            - "/home/isofh/server/his/his-app-8081.conf:/home/isofh/his/app.conf"
            - "/home/isofh/server/his/files:/home/isofh/his/files"
            - "/home/isofh/server/his/vn.isofh.jr.design:/home/isofh/his/vn.isofh.jr.design"
            - "/home/isofh/server/his/log:/home/isofh/his/log"
            - "/home/isofh/server/his/stable-110.tar.gz:/home/isofh/source/his-app.tar.gz"
        ports:
            - "8080:8080"       
        resources:
            limits:
                cpus: '30'
                memory: '90g'
                memory-swap: '90g'
        logging:
            driver: "json-file"
            options:
                max-size: "100m"